name: jira

on:
  push:
    #pull_request:
      #types: [opened, reopened]
      #branches:
      #- master

jobs:
  build:
    name: Jira
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Login
      id: login
      uses: atlassian/gajira-login@v2.0.0
      env:
        JIRA_BASE_URL: ${{ secrets.JIRA_BASE_URL }}
        JIRA_USER_EMAIL: ${{ secrets.JIRA_USER_EMAIL }}
        JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}

    - name: Create ticket for new PR
      id: create
      uses: ./atlassian/gajira-create@master
      with:
        project: DIT
        issuetype: Task
        summary: |
          Pull request submitted for ${{ github.repository }} by ${{ github.actor }}
        description: |
          Compare branch

    - name: Log created issue
      run: echo "Issue ${{ steps.create.outputs.issue }} was created"
