name: jira_ticket

on:
  push:
    #pull_request:
    #  types: [opened, reopened]

jobs:
  build:
    runs-on: ubuntu-latest
    needs: login
    steps:
    - uses: actions/checkout@v2
    - name: Create ticket for new PR
      id: create
      uses: ./atlassian/gajira-create@master
      with:
        project: DIT
        issuetype: Task
        summary: |
          Pull request submitted for ${{ github.repository }} by ${{ github.actor }}
        description: |
          Compare branch

    - name: Log created issue
      run: echo "Issue ${{ steps.create.outputs.issue }} was created"
