name: jira_ticket

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Create ticket for new PR
      id: create
      uses: ./atlassian/gajira-create@master
      with:
        project: DIT
        issuetype: Task
        summary: |
          Pull request submitted for ${{ github.repository }} by ${{ github.actor }}
        description: |
          Compare branch

    - name: Log created issue
      run: echo "Issue ${{ steps.create.outputs.issue }} was created"
