# This is a basic workflow to help you get started with Actions

name: jira

on:
  pull_request:
    branches:
    - master

jobs:
  build:
    runs-on: ubuntu-latest
    name: Jira
    steps:
    - name: Setup Jira
      uses: atlassian/gajira-cli@v2.0.1
      with:
        version: 1.0.20
    - name: Jira Login
      uses: atlassian/gajira-login@master
      env:
        JIRA_BASE_URL: ${{ secrets.JIRA_BASE_URL }}
        JIRA_USER_EMAIL: ${{ secrets.JIRA_USER_EMAIL }}
        JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}
    - name: Jira Create issue
      uses: atlassian/gajira-create@v2.0.0
      with:
        project: DIT
        issuetype: Bug
        summary: |
          Pull request submitted for ${{ github.repository }} by ${{ github.actor }}
        description: |
          Compare branch

    - name: Log created issue
      run: echo "Issue ${{ steps.create.outputs.issue }} was created"
